### PR TITLE
Add an option to disable browser auto launch

### PR DESCRIPTION
**Pull request by Rodziu**
I added this possibility by setting the --no-browser flag

### CODE REVIEW

**Comment by lukejacksonn** [comment]
Thanks for taking the time to address this! I like the way you have parsed out the flags from the command. Maybe we could make this more generic and add support for other flags like port which was requested in #11.

**Comment by lukejacksonn** [comment]
#15 is also relevant here I think

**Comment by mrozbarry** [comment]
Ah, should have looked at PRs, #17

**Comment by Rodziu** [comment]
I've updated my PR - now it allows you to change every option (plus the special '--no-browser' option) via flag and it's backward compatible :)
For example: `servor --reload-port 3000 dist index.html`

**Comment by lukejacksonn** [comment]
Thanks for this! Shame how much more verbose this makes the input parsing but I guess that is something we can optimise. I will have to decide between this PR and #15. I might end up cherry pick commits from both into a local branch and tweaking slightly before merging.

**Comment by lukejacksonn** [comment]
Hey man 👋thanks for trying this out. I recently merged some changes and I tried really hard to keep these commits in so that you were listed as a contributor still.. but then I hit squash and merge (doh) so I apologies for that 🙏

Anyway named arguments are now supported and I have done a release, so I'll close this!

**Pull request closed without merging**
