### PR TITLE
There's a really nice fork out there.

### PR DESCRIPTION
**Pull request by Raiondesu**
It allows CORS to be handled by the server.

### CODE REVIEW

**Comment by lukejacksonn** [comment]
Hey 👋 I never saw this! I just merged #4 and saw this here, sorry about that. Humm, this does seem like a good addition too. Can you see any reason as why not to do this?

**Comment by Raiondesu** [comment]
I mean... How can SPA suffer from CORS? Even if it's not used.
My team needs it to locally test SPAs in "production" environment before pushing changes, for example.

On the second thought, some servers may be set to reject requests with CORS headers.
For such a case, maybe make this an option? Like `-c` or `--cors`.

**Comment by lukejacksonn** [comment]
Yeh, I was wondering what situation you needed to pull on an SPA server for resources 🤔

**Comment by lukejacksonn** [comment]
Yo man 👋🏼I finally got round to refactoring this whole project. This feature has since been added here https://github.com/lukejacksonn/servor/blob/master/servor.js#L51.

The server now has file watching and live reloading capabilities ♻️

**Pull request closed without merging**
