### PR TITLE
Use named arguments

### LINKED ISSUE #11: Specify port without fallback?
I appreciate the simplicity of the command without too many flags, but I change the port much often than I change the fallback file. In fact, I've never changed the fallback file :sweat_smile: 

Would love to see `--port` so I can do `yarn servor dist --port 3001` instead of `yarn servor dist dist/index.html 3001`.

### PR DESCRIPTION
**Pull request by ziishaned**
Resolves #11

### CODE REVIEW

**Comment by lukejacksonn** [comment]
I like the options object. This is a breaking change though.. I wonder if it would be acceptable to have both positional arguments and names arguments.. they shouldn't conflict, right?

**Comment by lazarljubenovic** [comment]
> I wonder if it would be acceptable to have both positional arguments and names arguments.. they shouldn't conflict, right?

Well, someone _could_ have a project/dir/file called `--port` I guess...

**Comment by ziishaned** [comment]
@lukejacksonn there is no need for the positional arguments as we have default values for each argument.

**Comment by lukejacksonn** [comment]
@ziishaned the advantages that come with retaining positional args are no breaking change and an option for a less verbose invocation of all options, for example:

```
npx servor --directory="www" --fallback="index.html" --port="8080" --reloadPort="5000"
```
vs
```
npx servor www index.html 8080 5000
```

Thanks for cleaning up the diff, I will give this PR some good consideration this week.

**Comment by lukejacksonn** [comment]
Hey man 👋thanks for trying this out. I recently merged some changes and I tried really hard to keep these commits in so that you were listed as a contributor still.. but then I hit squash and merge (doh) so I apologies for that 🙏

Anyway named arguments are now supported and I have done a release, so I'll close this!

**Pull request closed without merging**
